version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-2u7nagiwnb45"
s3_prefix = "Test"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
